version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/qna_prod
      - PORT=3000
    depends_on:
      - mongo

volumes:
  mongo_data:
